# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordList
                                 A QGIS plugin
 CoordList
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-04
        copyright            : (C) 2019 by Lebedev
        email                : lebedev77@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordList class from file CoordList.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coord_list import CoordList
    return CoordList(iface)
